% root = 'F:\MHDO_Tracking\data\Janelia_Q1_2014\RingLED\MPEG4\Extracted_Clips';
[filename_data, pathname_data, ext_data] = uigetfile('*.txt','Select the video file to extract frames.');
data = dlmread(filename_data);
kinData.fps = 145.00;
kinData.microntopixel = 3;
kinData.stageposition(:,1) = data(:,2);
kinData.stageposition(:,2) = data(:,3);
kinData.fourier = data(:,10:end);
kinData.contour = fouri